# Generated by Django 4.2.6 on 2023-12-01 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nightclub',
            new_name='Club',
        ),
        migrations.RenameField(
            model_name='openinghours',
            old_name='nightclub',
            new_name='Club',
        ),
    ]
