# Generated by Django 4.2.6 on 2023-12-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_nightclub_club_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='club',
            name='music_type',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
    ]
